
spring:
  datasource:
    url: jdbc:mysql://49.235.113.36:3306/stocks_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Joesea123!@#
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 500

﻿mybatis:
#  # mybatis配置文件所在路径
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  # 所有Entity别名类所在包
#  type-aliases-package: com.grgbanking.**.entity
#  # mapper映射文件
  mapper-locations: classpath:mybatis/mappers/mysql/**/*.xml

# 股票实时数据下载接口地址
stock.curdata.down.host: http://hq.sinajs.cn/list=

# 股票历史数据下载配置
# host: 下载地址
# fields: 下载字段，多个字段以分号间隔（不配置默认为全部字段: TCLOSE;HIGH;LOW;TOPEN;LCLOSE;CHG;PCHG;TURNOVER;VOTURNOVER;VATURNOVER;TCAP;MCAP）
# startTime: 起始时间（不配置默认为19900101）
# endTime: 结束时间（不配置默认为当前时间）
# localDir: csv文件保存路径（不配置默认当前目录下的stockHisData）
# maxQueueTaskSize: 解析csv文件最大线程数（不配置默认为5）
stock.hisdata.down:
    host: http://quotes.money.163.com/service/chddata.html
    #fields: TCLOSE;HIGH;LOW;TOPEN;LCLOSE;CHG;PCHG;TURNOVER;VOTURNOVER;VATURNOVER;TCAP;MCAP
    startTime: 19900101
    #endTime: 20190621
    localDir: /Users/joesealea/IdeaProjects/stocksMarket/stockHisDataCsv
    maxQueueTaskSize: 5

#logging.level.com.stocksmarket.dao: debug
logging:
  config: classpath:logback.xml
  level:
    com.joesea.stocksmarket.dao: info


