
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stocksMarket?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

﻿mybatis:
#  # mybatis配置文件所在路径
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  # 所有Entity别名类所在包
#  type-aliases-package: com.grgbanking.**.entity
#  # mapper映射文件
  mapper-locations: classpath:mybatis/mappers/mysql/**/*.xml

stock:
  curdata:
    down:
      host: http://hq.sinajs.cn/list=

#logging.level.com.joesea.stocksmarket.dao: debug
logging:
  config: classpath:logback.xml
  level:
    com.joesea.stocksmarket.dao: debug


